# permissions for end users to edit performancetests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: performancetest-editor-role
rules:
- apiGroups:
  - specs.pti-spec.io
  resources:
  - performancetests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - specs.pti-spec.io
  resources:
  - performancetests/status
  verbs:
  - get
