# permissions for end users to view performancetests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: performancetest-viewer-role
rules:
- apiGroups:
  - specs.pti-spec.io
  resources:
  - performancetests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - specs.pti-spec.io
  resources:
  - performancetests/status
  verbs:
  - get
