# permissions for end users to view performancetestruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: performancetestrun-viewer-role
rules:
- apiGroups:
  - specs.my.domain
  resources:
  - performancetestruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - specs.my.domain
  resources:
  - performancetestruns/status
  verbs:
  - get
